version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
    environment:
      - NODE_ENV=development
      - MONGO_USER=samjeev
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev

  
